# Generated by Django 3.2.8 on 2022-04-12 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220413_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 0, 26, 44, 886701), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 0, 26, 44, 886701), verbose_name='Start Date'),
        ),
    ]
