# Generated by Django 3.2.8 on 2022-07-15 17:13

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220707_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Must be using following format +44 1234 567 890', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 18, 13, 38, 862824), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 18, 13, 38, 862824), verbose_name='Start Date'),
        ),
    ]
